# Generated by Django 4.0 on 2022-01-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
