# Generated by Django 4.0 on 2022-01-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.BigIntegerField(default=0),
        ),
    ]
